HRNET:
  HRNET_TYPE: 48
  NUM_KPTS: 29
  NORM_TYPE: 'softmax'
  DEPTH_DIM: 64
  HEIGHT_DIM: 64
  WIDTH_DIM: 64
  FLIP_HM: True
TEMPORAL_TRANS:
  FEATURE_DIM: 87
  NUM_HEADS: 3
  NUM_LAYERS: 1
  DROPOUT: 0.1
TEMPORAL_TRANS_VEC:
  FEATURE_DIM: 2048
  NUM_HEADS: 8
  NUM_LAYERS: 1
  DROPOUT: 0.1
VIDEO:
  FOCAL_LENGTH: 1000
  INPUT_SIZE: 256
  DEPTH_FACTOR: 2.2
  WINDOW_SIZE: 5
  J_REGRESSOR: './models/smil/J_regressor_h36m.npy'
  SMIL_FILE: './models/smil/smil_web.pkl'
TRANSFORM:
  SCALE_FACTOR: 0.3
  COLOR_FACTOR: 0.2
  OCCLUSION: True
  IMAGE_SIZE:
  - 256
  - 256
  HEATMAP_SIZE:
  - 64
  - 64
  DEPTH_DIM: 64
  BBOX_3D_SHAPE:
    - 2200
    - 2200
    - 2200
  ROT_FACTOR: 30
  SIGMA: 2
  LOSS_TYPE: 'LaplaceLossDimSMPLCam'